(
    program
    (
        comment
    )
    (
        import_or_export
        (
            library_export
            (
                configurable_uri
                (
                    uri
                    (
                        string_literal
                    )
                )
            )
        )
    )
    (
        comment
    )
    (
        class_definition
        name:
        (
            identifier
        )
        body:
        (
            class_body
            (
                declaration
                (
                    final_builtin
                )
                (
                    type_identifier
                )
                (
                    initialized_identifier_list
                    (
                        initialized_identifier
                        (
                            identifier
                        )
                    )
                )
            )
            (
                declaration
                (
                    final_builtin
                )
                (
                    type_identifier
                )
                (
                    initialized_identifier_list
                    (
                        initialized_identifier
                        (
                            identifier
                        )
                    )
                )
            )
            (
                declaration
                (
                    final_builtin
                )
                (
                    type_identifier
                )
                (
                    nullable_type
                )
                (
                    initialized_identifier_list
                    (
                        initialized_identifier
                        (
                            identifier
                        )
                    )
                )
            )
            (
                declaration
                (
                    constant_constructor_signature
                    (
                        const_builtin
                    )
                    (
                        identifier
                    )
                    (
                        formal_parameter_list
                        (
                            optional_formal_parameters
                            (
                                formal_parameter
                                (
                                    constructor_param
                                    (
                                        this
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    constructor_param
                                    (
                                        this
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    constructor_param
                                    (
                                        this
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
    (
        comment
    )
    (
        class_definition
        name:
        (
            identifier
        )
        superclass:
        (
            superclass
            (
                type_identifier
            )
        )
        body:
        (
            class_body
            (
                declaration
                (
                    final_builtin
                )
                (
                    type_identifier
                )
                (
                    nullable_type
                )
                (
                    initialized_identifier_list
                    (
                        initialized_identifier
                        (
                            identifier
                        )
                    )
                )
            )
            (
                declaration
                (
                    final_builtin
                )
                (
                    type_identifier
                )
                (
                    initialized_identifier_list
                    (
                        initialized_identifier
                        (
                            identifier
                        )
                    )
                )
            )
            (
                declaration
                (
                    constant_constructor_signature
                    (
                        const_builtin
                    )
                    (
                        identifier
                    )
                    (
                        formal_parameter_list
                        (
                            optional_formal_parameters
                            (
                                formal_parameter
                                (
                                    constructor_param
                                    (
                                        this
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    super_formal_parameter
                                    (
                                        super
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    super_formal_parameter
                                    (
                                        super
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    super_formal_parameter
                                    (
                                        super
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                            (
                                formal_parameter
                                (
                                    constructor_param
                                    (
                                        this
                                    )
                                    (
                                        identifier
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)
